### ISSUE TITLE
doc.getElementsByClassName; Could be outdated

### ISSUE THREAD

**Issue by DavidCharif** [tomer8007/wikipedia-to-json#2]
_At least with the new variable_ 
                      **var doc = new JSDOM(html);**
 _Old one was_   **var doc = jsdom(html);**
then to get access to the elements you need to access with window.

doc.window.document.getElementsByClassName...
________________________________________________________________________________________

After working a little i find a better solution. Just **var doc = new JSDOM(html).window.document;**
then you can doc.getElements..

**Comment by tomer8007** [comment]
Thank you, this is now fixed
